---
- name: Настройка DNS-сервера и клиентов
  hosts: all
  become: yes
  vars:
    dns_zone: "beloshenko.domain"
    dns_records:
      - { name: "@", ip: "192.168.1.2", type: "A" }
      - { name: "ns1", ip: "192.168.1.2", type: "A" }

  tasks:
    - name: Установка пакетов BIND
      dnf:
        name: [bind, bind-utils]
        state: present
      when: "'dns_servers' in group_names"

    - name: Настройка named.conf
      template:
        src: "/etc/ansible/roles/dns/templates/named.conf.j2"
        dest: "/etc/named.conf"
        owner: root
        group: named
        mode: 0640
      notify: restart named
      when: "'dns_servers' in group_names"
      
    - name: Создание файла зоны
      template:
        src: "/etc/ansible/roles/dns/templates/zone.example.j2"
        dest: "/var/named/{{ dns_zone }}.zone"
        owner: root
        group: named
        mode: 0640
      notify: restart named
      when: "'dns_servers' in group_names"

    - name: Настройка DNS-клиентов
      nmcli:
        conn_name: "enp0s3"
        dns4: "{{ dns_server }}"
        dns4_search: "{{ dns_zone }}"
        state: present
      when: "'dns_servers' not in group_names"
      notify: restart network

  handlers:
    - name: restart named
      systemd:
        name: named
        state: restarted
        
    - name: enable named
      systemd:
        name: named
        state: enabled
        
    - name: restart network
      systemd:
        name: NetworkManager
        state: restarted