---
- name: Configure and deploy DNS server
  hosts: dns_servers
  become: yes
  vars:
    dns_zone: "beloshenko.domain"
    dns_records:
      - { name: "@", ip: "192.168.1.2", type: "A" }
      - { name: "ns1", ip: "192.168.1.2", type: "A" }

  tasks:
    - name: Install BIND packages
      dnf:
        name: [bind, bind-utils]
        state: present

    - name: Configure named.conf
      template:
        src: "roles/dns/templates/named.conf.j2"
        dest: "/etc/named.conf"
        owner: root
        group: named
        mode: 0640
      notify: restart named

    - name: Create zone file
      template:
        src: "roles/dns/templates/zone.example.com.j2"
        dest: "/var/named/{{ dns_zone }}.zone"
        owner: root
        group: named
        mode: 0640
      notify: reload named

    - name: Enable and start named service
      systemd:
        name: named
        state: started
        enabled: yes

  handlers:
    - name: restart named
      systemd:
        name: named
        state: restarted

    - name: reload named
      systemd:
        name: named
        state: reloaded