---
- name: Configure and deploy NTP server and clients
  hosts: all
  become: yes
  vars:
    ntp_servers:
      - "0.ru.pool.ntp.org"
      - "1.ru.pool.ntp.org"
      - "2.ru.pool.ntp.org"

  tasks:
    - name: Install chrony package
      dnf:
        name: chrony
        state: present
      when: "'ntp_servers' in group_names"

    - name: Configure chrony server
      template:
        src: "/etc/ansible/roles/ntp/templates/ntp.conf.j2"
        dest: "/etc/chrony.conf"
        owner: root
        group: root
        mode: 0644
      notify: restart chronyd
      when: "'ntp_servers' in group_names"

    - name: Configure NTP clients
      template:
        src: "/etc/ansible/roles/ntp/templates/ntp-client.conf.j2"
        dest: "/etc/chrony.conf"
        owner: root
        group: root
        mode: 0644
      notify: restart chronyd
      when: "'ntp_servers' not in group_names"

  handlers:
    - name: restart chronyd
      systemd:
        name: chronyd
        state: restarted